name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Create version.json
        run: |
          echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > aptly-manage/version.json
      - name: Create tar
        run: tar -czf aptly-manage_${{ env.RELEASE_VERSION }}.tar.gz aptly-manage
      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: aptly-manage_${{ env.RELEASE_VERSION }}
          path: aptly-manage_${{ env.RELEASE_VERSION }}.tar.gz
